- name: Debug Inventory Variables
  hosts: all
  gather_facts: no
  tasks:
    - name: Show me the IPs
      debug:
        msg: 
          - "Node Name: {{ inventory_hostname }}"
          - "Public IP (ansible_host): {{ ansible_host }}"
          - "Internal IP (internal_ip): {{ internal_ip }}"
