plugin: google.cloud.gcp_compute
projects:
  - "hello-tofu"
auth_kind: application
zones:
  - "us-east1-b"
hostnames:
  - name
groups:
  # This group name MUST match the filename in group_vars/
  rdma_testers: "'rdma-tester' in (labels.role | default([]))"
